version: "3.7"

services:
  postgresDB: 
    image: postgres
    container_name: postgres_starter
    ports:
      - 5432:5432
    volumes:
      - postgres_starter:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis
    container_name: redis_starter
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      
volumes:
  postgres_starter:
  redis-data: